// bricks/web-angular-module/__brick__/example.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FlutterEmbeddingViewComponent } from './src/flutter-embedding-view.component';
import { FlutterEmbeddingApp, FlutterEmbeddingState, MyRpcTransport } from './src';
import { FlutterEmbeddingService } from './src/flutter-embedding.service';

// Example usage of the Flutter Angular Embedding Module
@Component({
    selector: 'app-example',
    standalone: true,
    imports: [CommonModule, FlutterEmbeddingViewComponent],
    template: `
        <div style="padding: 20px;">
            <h1>Flutter Angular Embedding Example</h1>

            <div style="margin-bottom: 20px;">
                <button
                    (click)="toggleFlutter()"
                    style="margin-right: 10px;"
                >
                    {{ showFlutter ? 'Hide' : 'Show' }} Flutter View
                </button>

                <select
                    [value]="language"
                    (change)="onLanguageChange($event)"
                    style="margin-right: 10px;"
                >
                    <option value="en">English</option>
                    <option value="es">Spanish</option>
                    <option value="fr">French</option>
                </select>

                <select
                    [value]="themeMode"
                    (change)="onThemeModeChange($event)"
                >
                    <option value="light">Light</option>
                    <option value="dark">Dark</option>
                </select>
            </div>

            <div *ngIf="showFlutter" style="height: 600px;">
                <flutter-embedding-view
                    [onInvokeHandover]="handleInvokeHandover"
                    [handoverServices]="[]"
                    [initState]="handleInitState"
                    className="example-flutter-view"
                ></flutter-embedding-view>
            </div>
        </div>
    `
})
export class ExampleComponent {
    showFlutter = false;
    language = 'en';
    themeMode = 'light';

    constructor(private flutterEmbeddingService: FlutterEmbeddingService) {}

    toggleFlutter() {
        this.showFlutter = !this.showFlutter;
    }

    onLanguageChange(event: Event) {
        this.language = (event.target as HTMLSelectElement).value;
    }

    onThemeModeChange(event: Event) {
        this.themeMode = (event.target as HTMLSelectElement).value;
    }

    handleInvokeHandover = (method: string, args: unknown): string => {
        console.log('Invoke handover:', method, args);
        return '';
    }

    handleInitState = (state: FlutterEmbeddingState, rpcTransport: MyRpcTransport) => {
        console.log('Flutter state initialized', state, rpcTransport);
        // You can use the state to change language, theme, etc.
        if (this.language) {
            state.changeLanguage(this.language);
        }
        if (this.themeMode) {
            state.changeThemeMode(this.themeMode);
        }
    }
}

// bricks/web-react-module/__brick__/example.tsx
import React, { useState } from 'react';
import { FlutterApp, FlutterView } from './src';

// Example usage of the Flutter React Embedding Module
function ExampleApp() {
    const [showFlutter, setShowFlutter] = useState(false);
    const [language, setLanguage] = useState('en');
    const [themeMode, setThemeMode] = useState('light');

    // Mock Flutter app instance
    const flutterApp: FlutterApp = {
        addView: (options: { hostElement: HTMLElement | null }) => {
            console.log('Adding Flutter view to element:', options.hostElement);
            // In a real implementation, this would initialize the Flutter app
            // and return a view ID
            return 1;
        },
        removeView: (viewId: number) => {
            console.log('Removing Flutter view:', viewId);
            // In a real implementation, this would clean up the Flutter view
        }
    };

    return (
        <div style={{ padding: '20px' }}>
            <h1>Flutter React Embedding Example</h1>

            <div style={{ marginBottom: '20px' }}>
                <button
                    onClick={() => setShowFlutter(!showFlutter)}
                    style={{ marginRight: '10px' }}
                >
                    {showFlutter ? 'Hide' : 'Show'} Flutter View
                </button>

                <select
                    value={language}
                    onChange={(e) => setLanguage(e.target.value)}
                    style={{ marginRight: '10px' }}
                >
                    <option value="en">English</option>
                    <option value="es">Spanish</option>
                    <option value="fr">French</option>
                </select>

                <select
                    value={themeMode}
                    onChange={(e) => setThemeMode(e.target.value)}
                >
                    <option value="light">Light</option>
                    <option value="dark">Dark</option>
                </select>
            </div>

            {showFlutter && (
                <FlutterView
                    flutterApp={flutterApp}
                    removeView={() => setShowFlutter(false)}
                    currentLanguage={language}
                    currentThemeMode={themeMode}
                    className="example-flutter-view"
                />
            )}
        </div>
    );
}

export default ExampleApp;
