// bricks/web-react-example/__brick__/src/App/App.tsx
//{{=<% %>=}}
import Box from '@mui/material/Box'
import Button from '@mui/material/Button'
import CssBaseline from '@mui/material/CssBaseline'
import Tab from '@mui/material/Tab'
import Tabs from '@mui/material/Tabs'
import Typography from '@mui/material/Typography'
import useMediaQuery from '@mui/material/useMediaQuery'
import {
  FlutterEmbeddingState,
  FlutterEmbeddingView,
  HandoversToFlutterServiceClient,
  Language,
  ThemeMode
} from '<% webReactPackageName %>'
import React from 'react'
import CommunicationView, { CommunicationViewMethods } from './CommunicationView'

interface View {
  id: number
  state: FlutterEmbeddingState | null
  handoversToFlutterServiceClient: HandoversToFlutterServiceClient | null
}

function App() {
  // Responsive layout: >= 600 is side-by-side, < 600 is tabs
  const isLargeScreen = useMediaQuery('(min-width:600px)')
  const [selectedTab, setSelectedTab] = React.useState(0)

  // State
  const [views, setViews] = React.useState<View[]>([])

  // Ref to CommunicationView methods
  const communicationViewMethodsRef = React.useRef<CommunicationViewMethods | null>(null)

  // Derived state - engine is "running" when there are views
  const hasViews = views.length > 0

  const addView = () => {
    setViews((flutterViewKeys) => {
      return [
        ...flutterViewKeys,
        {
          id: (flutterViewKeys[flutterViewKeys.length - 1]?.id ?? 0) + 1,
          state: null,
          handoversToFlutterServiceClient: null
        }
      ]
    })
  }

  const removeView = (id: number) => {
    setViews((flutterViewKeys) => flutterViewKeys.filter(k => k.id !== id))
  }

  const handleTabChange = (_event: React.SyntheticEvent, newValue: number) => {
    setSelectedTab(newValue)
  }

  const handoversToFlutterServiceClients = views
    .map(v => v.handoversToFlutterServiceClient)
    .filter((client): client is HandoversToFlutterServiceClient => client !== null)

  // Settings Panel Content
  const SettingsPanel = (
    <Box sx={{
      height: '100%',
      overflow: 'auto',
      p: 2,
      borderRight: isLargeScreen ? '1px solid #e0e0e0' : 'none'
    }}>
      <Typography variant="h5" component="h2" gutterBottom>
        <% flutterEmbeddingName %> Demo
      </Typography>

      <Button
        fullWidth
        variant="contained"
        onClick={addView}
        sx={{ mb: 2 }}
      >
        Add Flutter view
      </Button>

      <CommunicationView
        hasViews={hasViews}
        handoversToFlutterServiceClients={handoversToFlutterServiceClients}
        onRemoveView={removeView}
        methodsRef={communicationViewMethodsRef}
      />
    </Box>
  )

  // Flutter Container Content
  const FlutterContainer = (
    <Box sx={{
      height: '100%',
      display: 'flex',
      flexDirection: 'column',
      backgroundColor: '#f0f0f0',
      overflow: 'hidden'
    }}>
      {views.length === 0 ? (
        <Box sx={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          height: '100%',
          color: '#666'
        }}>
          <Typography variant="h6">Flutter container area</Typography>
        </Box>
      ) : (
        views.map((view) => (
          <Box key={view.id} sx={{
            flex: 1,
            display: 'flex',
            flexDirection: 'column',
            position: 'relative',
            minHeight: '300px',
            width: '100%'
          }}>
            <Box sx={{
              position: 'absolute',
              top: 8,
              right: 8,
              zIndex: 10
            }}>
              <Button
                variant="contained"
                size="small"
                color="error"
                onClick={() => removeView(view.id)}
              >
                Remove View {view.id}
              </Button>
            </Box>
            <FlutterEmbeddingView
              key={view.id}
              className="flutter-embedding-view"
              onInvokeHandover={(method: string, args: unknown) => {
                alert('Invoke handover: ' + method + ' ' + JSON.stringify(args))
                return 'Hello back to Flutter'
              }}
              startParams={communicationViewMethodsRef.current?.createStartParams() ?? { language: Language.EN, themeMode: ThemeMode.SYSTEM, environment: 'MOCK' }}
              handoversToHostService={communicationViewMethodsRef.current!.createHandoversToHostService(view.id)}
              initState={(state: FlutterEmbeddingState, handoversToFlutterServiceClient: HandoversToFlutterServiceClient) => {
                setViews(prevViews => prevViews.map(v =>
                  v.id === view.id
                    ? { ...v, state, handoversToFlutterServiceClient }
                    : v
                ))
              }}
            />
          </Box>
        ))
      )}
    </Box>
  )

  return (
    <Box sx={{ display: 'flex', flexDirection: 'column', height: '100vh', overflow: 'hidden' }}>
      <CssBaseline />

      {isLargeScreen ? (
        // Large screen: Side-by-side layout
        <Box sx={{ display: 'flex', flex: 1, overflow: 'hidden' }}>
          <Box sx={{ width: 400, flexShrink: 0, overflow: 'auto' }}>
            {SettingsPanel}
          </Box>
          <Box sx={{ flex: 1, overflow: 'hidden' }}>
            {FlutterContainer}
          </Box>
        </Box>
      ) : (
        // Small screen: Tabbed layout
        <Box sx={{ display: 'flex', flexDirection: 'column', height: '100vh', overflow: 'hidden', width: '100%' }}>
          <Tabs
            value={selectedTab}
            onChange={handleTabChange}
            variant="fullWidth"
            sx={{ borderBottom: 1, borderColor: 'divider' }}
          >
            <Tab label="Settings" />
            <Tab label="Flutter" />
          </Tabs>
          <Box sx={{ flex: 1, overflow: 'hidden' }}>
            {selectedTab === 0 ? (
              <Box sx={{ height: '100%', overflow: 'auto' }}>
                {SettingsPanel}
              </Box>
            ) : (
              FlutterContainer
            )}
          </Box>
        </Box>
      )}
    </Box>
  )
}

export default App

// bricks/web-angular-example/__brick__/src/app/app.component.ts
//{{=<% %>=}}
import {
  FlutterEmbeddingState,
  FlutterEmbeddingViewComponent,
  HandoversToFlutterServiceClient
} from '<% webAngularPackageName %>';
import { BreakpointObserver } from '@angular/cdk/layout';
import { CommonModule } from '@angular/common';
import { Component, ViewChild } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatTabsModule } from '@angular/material/tabs';
import { CommunicationViewComponent } from './app.communicationview.component';

interface View {
  id: number;
  state: FlutterEmbeddingState | null;
  handoversToFlutterServiceClient: HandoversToFlutterServiceClient | null;
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatButtonModule,
    MatTabsModule,
    FlutterEmbeddingViewComponent,
    CommunicationViewComponent
  ],
  template: `
    <div style="display: flex; flex-direction: column; height: 100vh; overflow: hidden;">
      <ng-container *ngIf="isLargeScreen; else smallScreenLayout">
        <!-- Large screen: Side-by-side layout -->
        <div style="display: flex; flex: 1; overflow: hidden;">
          <!-- Settings Panel -->
          <div style="width: 400px; flex-shrink: 0; overflow: auto; border-right: 1px solid #e0e0e0;">
            <div style="height: 100%; overflow: auto; padding: 16px;">
              <h1><% flutterEmbeddingName %> Demo</h1>
              
              <button mat-raised-button color="primary" (click)="addView()" style="width: 100%; margin-bottom: 16px;">
                Add Flutter view
              </button>

              <app-communication-view
                #communicationView
                [hasViews]="hasViews"
                [handoversToFlutterServiceClients]="handoversToFlutterServiceClients"
                [onRemoveView]="removeView.bind(this)"
              ></app-communication-view>
            </div>
          </div>

          <!-- Flutter Container -->
          <div style="flex: 1; overflow: hidden;">
            <div style="height: 100%; display: flex; flex-direction: column; background-color: #f0f0f0; overflow: hidden;">
              <div *ngIf="views.length === 0" style="display: flex; align-items: center; justify-content: center; height: 100%; color: #666;">
                <h2>Flutter container area</h2>
              </div>
              
              <div *ngFor="let view of views" style="flex: 1; display: flex; flex-direction: column; position: relative; min-height: 300px; width: 100%;">
                <div style="position: absolute; top: 8px; right: 8px; z-index: 10;">
                  <button mat-raised-button color="warn" (click)="removeView(view.id)">
                    Remove View {{ view.id }}
                  </button>
                </div>
                
                <flutter-embedding-view
                  className="flutter-embedding-view"
                  [onInvokeHandover]="handleInvokeHandover"
                  [startParams]="communicationView.createStartParams()"
                  [handoversToHostService]="communicationView.createHandoversToHostService(view.id)"
                  [initState]="handleInitState(view)"
                ></flutter-embedding-view>
              </div>
            </div>
          </div>
        </div>
      </ng-container>

      <!-- Small screen: Tabbed layout -->
      <ng-template #smallScreenLayout>
        <div style="display: flex; flex-direction: column; height: 100vh; overflow: hidden; width: 100%;">
          <mat-tab-group [(selectedIndex)]="selectedTabIndex" style="flex: 1;">
            <mat-tab label="Settings">
              <div style="height: 100%; overflow: auto; padding: 16px;">
                <h1><% flutterEmbeddingName %> Demo</h1>
                
                <button mat-raised-button color="primary" (click)="addView()" style="width: 100%; margin-bottom: 16px;">
                  Add Flutter view
                </button>

                <app-communication-view
                  #communicationView
                  [hasViews]="hasViews"
                  [handoversToFlutterServiceClients]="handoversToFlutterServiceClients"
                  [onRemoveView]="removeView.bind(this)"
                ></app-communication-view>
              </div>
            </mat-tab>
            
            <mat-tab label="Flutter">
              <div style="height: 100%; display: flex; flex-direction: column; background-color: #f0f0f0; overflow: hidden;">
                <div *ngIf="views.length === 0" style="display: flex; align-items: center; justify-content: center; height: 100%; color: #666;">
                  <h2>Flutter container area</h2>
                </div>
                
                <div *ngFor="let view of views" style="flex: 1; display: flex; flex-direction: column; position: relative; min-height: 300px; width: 100%;">
                  <div style="position: absolute; top: 8px; right: 8px; z-index: 10;">
                    <button mat-raised-button color="warn" (click)="removeView(view.id)">
                      Remove View {{ view.id }}
                    </button>
                  </div>
                  
                  <flutter-embedding-view
                    className="flutter-embedding-view"
                    [onInvokeHandover]="handleInvokeHandover"
                    [startParams]="communicationView.createStartParams()"
                    [handoversToHostService]="communicationView.createHandoversToHostService(view.id)"
                    [initState]="handleInitState(view)"
                  ></flutter-embedding-view>
                </div>
              </div>
            </mat-tab>
          </mat-tab-group>
        </div>
      </ng-template>
    </div>
  `,
  styles: [`
    :host {
      height: 100vh;
      display: block;
    }
  `]
})
export class AppComponent {
  @ViewChild('communicationView') communicationView!: CommunicationViewComponent;

  views: View[] = [];
  selectedTabIndex: number = 0;
  isLargeScreen: boolean = false;

  // Derived state
  get hasViews(): boolean {
    return this.views.length > 0;
  }

  get handoversToFlutterServiceClients(): HandoversToFlutterServiceClient[] {
    return this.views
      .map(v => v.handoversToFlutterServiceClient)
      .filter((client): client is HandoversToFlutterServiceClient => client !== null);
  }

  constructor(private breakpointObserver: BreakpointObserver) {
    this.breakpointObserver.observe(['(min-width: 600px)']).subscribe((result: { matches: boolean }) => {
      this.isLargeScreen = result.matches;
    });
  }

  addView() {
    const newId = this.views.length > 0
      ? (this.views[this.views.length - 1]?.id ?? 0) + 1
      : 1;
    this.views = [
      ...this.views,
      {
        id: newId,
        state: null,
        handoversToFlutterServiceClient: null
      }
    ];
  }

  removeView(id: number) {
    this.views = this.views.filter(v => v.id !== id);
  }

  handleInvokeHandover = (method: string, args: unknown): string => {
    alert('Invoke handover: ' + method + ' ' + JSON.stringify(args));
    return 'Hello back to Flutter';
  }

  handleInitState = (view: View) => {
    return (state: FlutterEmbeddingState, handoversToFlutterServiceClient: HandoversToFlutterServiceClient) => {
      view.state = state;
      view.handoversToFlutterServiceClient = handoversToFlutterServiceClient;
    };
  }
}
